version: 2

models:
  - name: int_fact_transaction
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null

      - name: customer_id
        tests:
          - not_null

      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('int_dim_products')
              field: product_id

      - name: quantity
        tests:
          - not_null

      - name: total_spent
        tests:
          - not_null

      - name: payment_method
        tests:
          - not_null
          - accepted_values:
              values: ['Cash', 'Credit Card', 'Digital Wallet']

      - name: location
        tests:
          - not_null

      - name: transaction_date
        tests:
          - not_null

  - name: int_dim_products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('int_fact_transaction')
              field: product_id

      - name: category
        tests:
          - not_null

      - name: item
        tests:
          - not_null

      - name: price
        tests:
          - not_null